name: CI Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    # Remove Gradle cache directory
    - name: Clear Gradle Cache
      run: |
        if [ "${{ runner.os }}" == "Linux" ] || [ "${{ runner.os }}" == "macOS" ]; then
          rm -rf ~/.gradle/caches
        elif [ "${{ runner.os }}" == "Windows" ]; then
          Remove-Item -Path $env:USERPROFILE\.gradle\caches -Recurse -Force
        fi
      shell: bash

    # Example step to build the project
    - name: Build with Gradle
      run: ./gradlew build
      shell: bash
